name: api_helper
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.18.0
  either_dart: ^1.0.0
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  http: ^1.2.1
  json_annotation: ^4.9.0
  tresastronautas_ui:
    path: ../tresastronautas_ui
  connectivity_plus: ^6.0.5
  equatable: ^2.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.11
  hive_generator: ^2.0.1
  path: ^1.9.0
  json_serializable: ^6.8.0
  freezed: ^2.5.2
  mocktail: ^1.0.4
  test: ^1.19.2
  get_it: ^7.7.0
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
